### ISSUE TITLE
运行后报错：ffi.Library Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by sincerefly** [wzdxy/electron-ffi-demo#1]
> ffi.Library Error: %1 is not a valid Win32 application.
\\?\E:\code\electron-ffi-demo\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (E:\code\electron-ffi-demo\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (E:\code\electron-ffi-demo\node_modules\ref\lib\ref.js:5:47)

**Comment by sincerefly** [comment]
对了，我的环境是

windows 7 
Python 2.7.14 32位
Node.js 32位

可能和位数有关系，请问你的Node.js是多少位的 @wzdxy

**Comment by sincerefly** [comment]
安装了Node.js 64位版本，可以了。

**Comment by wzdxy** [comment]
嗯 ，我的配置是 x64 的 ， 参见  `package.json` 中的 `scripts`
```
node-gyp rebuild --target=1.7.11 --arch=x64 --target_arch=x64 --dist-url=https://atom.io/download/electron
```

**Comment by sincerefly** [comment]
对了，package.json中使用^1.7.11，使用过程中会下载1.8.2版本（2018.02.27），会与node-gyp指定的target不匹配

建议在DLL文件夹内中提供一个32位的DLL，对于32位环境的测试者也能免去了自己编译DLL的环节
